### PR TITLE
Add basic macOS publishing scripts

### PR DESCRIPTION
**Pull request by Redth**
This build.cake is borrowed from ILSpy

The script adds support to create a .app bundle (and a few other zip artifacts) for publishing.

No work is yet done to try and pick up the artifacts in CI, or sign them.

For now users could clone and:

```
dotnet cake ./build-macosx.cake
open ./artifacts/Structured Log Viewer.app
```

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Awesome, I like it!

**Comment by Redth** [comment]
@KirillOsenkov can you assist with the appveyor stuff here? I think this is good to go except for getting appveyor to run the cake script, not sure what I've done wrong with the changes here...

**Comment by Redth** [comment]
@KirillOsenkov I think this is good to go now... The only thing I'm not sure how to improve is the artifact which is a .app.zip gets extracted automatically when you download on Mac where really you want it to remain a .app file... I guess it could be zipped differently to preserve the .app folder inside the zip....

**Comment by Redth** [comment]
There we go, that last commit did it.  We're all set now.

**Comment by KirillOsenkov** [comment]
Awesome, thanks a lot!

**Pull request merged**
