### PR TITLE
Migrate Themeing code to use a cascading parameter

### PR DESCRIPTION
**Pull request by Therzok**
Instead of manually invoking all the style setting code, use a cascading parameter.

This also cleans up a bit of the code, I intend to do a few more cleanups and adding theme storage setting and browser/OS detection soon.

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
Thanks!

**Comment by KirillOsenkov** [comment]
Hmm I'm getting these build errors in the live branch both locally and on CI:

image

Any idea why it works on your machine?

**Comment by KirillOsenkov** [comment]
@Therzok

**Comment by Therzok** [comment]
Yes, I know why. I forgot to commit a file.

**Pull request merged**
