### PR TITLE
Added TaskAssemblyLocation to TaskStartedEventArgs2

### LINKED ISSUE #771: Add support for task assembly location
Binlog will have a new value for task. It identifies assembly where the task is implemented.

I can do it after PR merge in MSBuild: https://github.com/dotnet/msbuild/pull/9948

Any ideas how/where should be visualize the new field?

### PR DESCRIPTION
**Pull request by MichalPavlik**
Fixes #771

### CODE REVIEW

**Comment by KirillOsenkov** [comment]
The reader looks good! Let's also update the BuildEventArgsWriter (same changes as in the MSBuild repo)

**Comment by KirillOsenkov** [comment]
Oh, also need to update this place:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/7e1ca2ae77eaee8e273e416c56aaaf72bd311f42/src/StructuredLogger/Construction/Construction.cs#L1154

Currently we compute the Task assembly by parsing Using Task messages here:
https://github.com/KirillOsenkov/MSBuildStructuredLog/blob/7e1ca2ae77eaee8e273e416c56aaaf72bd311f42/src/StructuredLogger/Construction/MessageProcessor.cs#L131-L139

We need to first take TaskStartedEventArgs2.TaskAssemblyLocation if that's not null or empty, otherwise fall back to the existing logic.

**Comment by MichalPavlik** [comment]
Yes, it did :)
https://github.com/dotnet/msbuild/pull/9948#discussion_r1555893907

I will update the MessageProcessor. I wanted to ask where can I find the code for populating Assembly node inside task, but you was faster :)

**Comment by KirillOsenkov** [comment]
Now just the writer please ;)

**Comment by KirillOsenkov** [comment]
@MichalPavlik could you please include the changes in our copy of BuildEventArgsWriter.cs as well?

**Comment by KirillOsenkov** [comment]
@MichalPavlik also please make sure the test `TestBinaryLoggerRoundtrip` is passing, it's failing with these changes

**Comment by MichalPavlik** [comment]
Sorry, I had vacation. I will do it today.

**Comment by MichalPavlik** [comment]
I was debugging the test locally and I'm confused by diff. It seems that the difference is in newline format:
image

I have to investigate more, but if you have any idea, please let me know. I don't think my changes would cause this kind of failure :|

**Comment by KirillOsenkov** [comment]
Perhaps @JanKrivanek can help here, he did a lot of work in making sure the format is roundtrippable.

**Comment by JanKrivanek** [comment]
The nullref exception is more concerning that the newline format - I'd suggest looking into that

**Comment by MichalPavlik** [comment]
Test result was misleading :) The root cause was in writer - test is using MSBuild to build project, but it knows nothing about `TaskStartedEventArgs2`, so the value was missing in binlog.

**Comment by JanKrivanek** [comment]
Lets make sure the test is catching the similar problems for the future: https://github.com/MichalPavlik/MSBuildStructuredLog/pull/1 (I do not have write access to your fork @MichalPavlik - so I created this as a PR to your branch :))

**Comment by MichalPavlik** [comment]
Great, thanks :)

**Review by KirillOsenkov — APPROVED** [review]
Thank you!

**Pull request merged**
